[package]
name = "irust"
version = "0.7.20"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = "0.12.1"
dirs = "2.0.2"
once_cell = "1.2.0"

[dependencies.syntect]
version = "3.3.0"
default-features = false
features = ["parsing", "assets", "dump-load-rs"]

[target.'cfg(unix)'.dependencies]
nix = "0.15.0"
